### ISSUE TITLE
Suppressed log types show up as empty lines

### ISSUE THREAD

**Issue by dacwe** [palantir/witchcraft-java-logging#38]
I have disabled metric and request logs in "Witchcraft Logging" settings. The log lines do not show up. Instead empty lines takes their place. 

See the screen recording below.

![output](https://user-images.githubusercontent.com/13199514/130811629-6ca7d6f7-b364-44b4-9ff1-4020254d0527.gif)

At the end of the recording the metric logs are outputted and the whole console is filled with blank lines.

### Versions

* IntelliJ IDEA 2021.2.1
* witchcraft-logging 2.7.0
* Ubuntu 20.04.2 LTS

**Comment by carterkozak** [comment]
#39 does the trick! I'll find somebody to review and we can cut a release shortly.

**Comment by dacwe** [comment]
Sweet, thanks!
